/* Temporary, role-separated iPad controls for every guided child activity. */
const LEActivityRemote=(()=>{
  let session=null,state=null,timer=null,busy=false,shown='',speech=-1,reviewing=false;
  const esc=v=>escapeHTML(v),by=id=>document.getElementById(id);
  function definition(id){const d=objectiveDefinitions.find(d=>d.id===id);if(!d)throw Error('This activity is unavailable. Refresh both screens.');return d.scenarios?{...d,tasks:d.scenarios.map(s=>({prompt:s.text,visual:scenarioIllustration(s),choices:s.choices,mode:'scenario'}))}:d;}
  function config(id){const d=definition(id);return {objective_id:id,tasks:d.tasks.map(t=>t.mode==='observed'?{mode:'observed'}:{mode:t.mode==='scenario'?'scenario':t.order?'order':'touch',choices:t.choices.length,...(t.order?{length:t.order.length}:{})})};}
  async function api(body){const r=await fetch(PAIR_API.replace('little-evidence-session','little-evidence-activity-session'),{method:'POST',headers:{'Content-Type':'application/json',apikey:PAIR_PUBLIC_KEY},body:JSON.stringify({...session,...body})});const data=await r.json();if(!r.ok)throw Error(data.error||'Connection interrupted');return data;}
  function status(text){let e=by('remoteConnection');if(!e){e=document.createElement('p');e.id='remoteConnection';e.setAttribute('role','status');guidedChild.append(e);}e.textContent=text;}
  function surface(){show('guidedObjectiveScreen');guidedHome.classList.add('hidden');guidedCheck.classList.add('hidden');guidedChild.classList.remove('hidden');document.querySelector('.app').classList.toggle('scenario-mode',session.role==='display');}
  function accept(next){if(state&&next.revision<state.revision)return;state=next;render();}
  async function action(action,extra={}){if(busy||!state)return;busy=true;const payload={action,revision:state.revision,prompt_index:state.prompt_index,...extra};try{const data=await api(payload);accept(data.state);if(data.conflict)status('Screen updated. Please try your action again.');}catch(e){status(e.message+' Your place is kept. Try again.');if(session.role==='display'){shown='';render();status(e.message+' Tap your answer again.');}}finally{busy=false;}}
  function poll(){clearTimeout(timer);if(!session)return;const current=session;api({action:'state'}).then(data=>{if(session===current){accept(data.state);if(!reviewing)status('● Connected');}}).catch(e=>{if(session===current)status('Reconnecting… '+e.message)}).finally(()=>{if(session===current)timer=setTimeout(poll,900)});}
  function render(){if(reviewing)return;if(session.role==='display'){if(state.speech_seq!==speech&&speech!==-1&&state.status==='active')by('taskHear')?.click();speech=state.speech_seq;}const key=state.config.objective_id+':'+state.status+':'+state.prompt_index+':'+(session.role==='teacher'?state.revision:'');if(key===shown)return;shown=key;surface();const d=definition(state.config.objective_id),t=d.tasks[state.prompt_index];
    if(session.role==='display'){
      document.body.classList.add('remote-child-display');
      if(state.status==='active'){activeDefinition=d;taskIndex=state.prompt_index;taskAnswers=structuredClone(state.responses);taskSequence=[];childTapReadyAt=Date.now()+350;renderChildTask();}
      else if(state.status==='complete')guidedChild.innerHTML='<section class="panel child-scenario celebration"><h1>Thank you for trying!</h1><p>You shared your ideas. Your teacher will choose what comes next.</p></section>';
      else if(!by('remotePairQr'))guidedChild.innerHTML='<section class="panel child-scenario"><h1>Ready when you are!</h1><p>Your teacher will start the activity from the iPad.</p></section>';
      if(state.speech_seq!==speech&&speech!==-1&&state.status==='active')by('taskHear')?.click();speech=state.speech_seq;return;
    }
    document.body.classList.remove('remote-child-display');by('modeTag').textContent='TEACHER IPAD · OBJECTIVE '+d.id;
    guidedChild.innerHTML='<section class="panel activity-prep"><p class="eyebrow">iPad remote · Objective '+esc(d.id)+'</p><h1>'+esc(d.family||d.title)+'</h1><p id="remoteConnection" role="status">● Connected</p>'+(state.status==='waiting'?'<p>When the child is ready, start the SmartBoard activity.</p><button id="remoteStart" class="primary">Start activity →</button>':state.status==='complete'?'<h2>Activity complete</h2><p>Continue to teacher review on this iPad to save your evidence.</p><button id="remoteReview" class="primary">Teacher review and save →</button><button id="remoteRetry" class="secondary">Repeat last prompt</button>':'<p>Prompt '+(state.prompt_index+1)+' of '+d.tasks.length+'</p><h2>'+esc(t.prompt)+'</h2>'+(t.note?'<p>'+esc(t.note)+'</p>':'')+(t.mode==='observed'?'<p>Watch or listen. Advance when you are ready.</p><label>Optional observation<select id="remoteObservation"><option value="not-observed">Not recorded / not enough evidence</option><option value="independent">Demonstrated independently</option><option value="supported">Demonstrated with support</option><option value="not-demonstrated">Not demonstrated this time</option></select></label><button id="remoteNext" class="primary">'+(state.prompt_index===d.tasks.length-1?'Complete activity ✓':'Next prompt →')+'</button>':'<p>The child’s selection advances automatically on the SmartBoard.</p>')+'<div class="guided-actions"><button id="remoteBack">Previous prompt</button><button id="remoteSpeak">Repeat direction</button><button id="remoteSkip">Skip this prompt →</button></div>')+'</section>';
    const bind=(id,fn)=>{if(by(id))by(id).onclick=fn};bind('remoteStart',()=>action('start'));bind('remoteNext',()=>action('observe',{observation:by('remoteObservation').value}));bind('remoteBack',()=>action('back'));bind('remoteSpeak',()=>action('speak'));bind('remoteSkip',()=>action('skip'));bind('remoteRetry',()=>action('retry'));bind('remoteReview',review);
  }
  function review(){const id=state.config.objective_id,d=objectiveDefinitions.find(d=>d.id===id),answers=structuredClone(state.responses);reviewing=true;clearTimeout(timer);if(d.scenarios)childEvidenceByObjective[id]={mode:'child_scenarios',answers};else childEvidenceByObjective[id]={mode:'touch',answers};openGuidedObjective(id);startGuidedInterview();history.replaceState(null,'',location.pathname+location.search);session=null;}
  async function start(id){try{const data=await api({action:'create',config:config(id)});session={id:data.id,role:'display',token:data.display_token};state=data.state;shown='';reviewing=false;surface();const url=new URL(location.href);url.hash='activityRemote='+data.id+'.'+data.teacher_token;const link=url.toString();history.replaceState(null,'','#activityDisplay='+data.id+'.'+data.display_token);guidedChild.innerHTML='<section class="panel activity-prep"><h1>Connect your iPad</h1><p>Scan this code with the iPad camera. Start and advance teacher-led prompts there. Child selections advance automatically.</p><div id="remotePairQr"></div><p><a id="remotePairLink">Open iPad remote</a></p><button id="remoteCopy">Copy iPad link</button><p id="remoteConnection">Waiting for your iPad…</p></section>';by('remotePairLink').href=link;by('remoteCopy').onclick=()=>navigator.clipboard.writeText(link).then(()=>toast('iPad link copied.')).catch(()=>toast('Scan the QR code with your iPad camera.'));const qr=window.qrcode(0,'M');qr.addData(link);qr.make();by('remotePairQr').innerHTML='<img alt="Scan with your iPad camera" src="'+qr.createDataURL(6,4)+'">';poll();}catch(e){toast(e.message);}}
  function button(container,id){if(!container||container.querySelector('[data-remote-start]'))return;const b=document.createElement('button');b.dataset.remoteStart='true';b.className='primary';b.textContent='Use iPad remote';b.onclick=()=>start(id);container.append(b);}
  function init(){const style=document.createElement('style');style.textContent='.remote-child-display #taskBack,.remote-child-display #taskSkip,.remote-child-display #taskNext,.remote-child-display .topbar,.remote-child-display #checkpointContext{display:none!important} #remotePairQr img{max-width:100%;width:280px} #remoteNext{display:block;margin:20px 0}';document.head.append(style);const match=location.hash.match(/^#activity(Remote|Display)=([0-9a-f-]{36})\.([A-Za-z0-9_-]{43})$/i);if(match){session={id:match[2],role:match[1].toLowerCase()==='remote'?'teacher':'display',token:match[3]};surface();guidedChild.innerHTML='<section class="panel"><h1>Connecting to your activity…</h1></section>';poll();}}
  return {init,start,button,isDisplay:()=>session?.role==='display',answer:()=>action('answer',{answer:taskAnswers[taskIndex]}),decorate:()=>{if(session?.role==='display')for(const id of ['taskBack','taskSkip','taskNext'])by(id).hidden=true;}};
})();
